"""empty message

Revision ID: 242fc3294ea2
Revises: 
Create Date: 2018-02-17 17:00:58.041709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '242fc3294ea2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=30), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('service', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('performed', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('periodic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('low_mileage', sa.Integer(), nullable=True),
    sa.Column('high_mileage', sa.Integer(), nullable=True),
    sa.Column('service', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preventive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('service', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preventive')
    op.drop_table('periodic')
    op.drop_table('maintenance')
    # ### end Alembic commands ###
