"""empty message

Revision ID: d42f43836b4f
Revises: 242fc3294ea2
Create Date: 2018-02-18 15:43:41.375408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd42f43836b4f'
down_revision = '242fc3294ea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['maintenance_id'], ['maintenance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('periodic', sa.Column('complete', sa.Boolean(), nullable=True))
    op.add_column('periodic', sa.Column('due', sa.Integer(), nullable=True))
    op.drop_column('periodic', 'description')
    op.drop_column('periodic', 'high_mileage')
    op.drop_column('periodic', 'low_mileage')
    op.add_column('preventive', sa.Column('time', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preventive', 'time')
    op.add_column('periodic', sa.Column('low_mileage', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('periodic', sa.Column('high_mileage', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('periodic', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('periodic', 'due')
    op.drop_column('periodic', 'complete')
    op.drop_table('product')
    # ### end Alembic commands ###
