"""empty message

Revision ID: df5ddb1ab1c3
Revises: d42f43836b4f
Create Date: 2018-02-18 16:24:18.650748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df5ddb1ab1c3'
down_revision = 'd42f43836b4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('make', sa.String(length=30), nullable=True),
    sa.Column('model', sa.String(length=30), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('vin', sa.Integer(), nullable=True),
    sa.Column('license', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle')
    # ### end Alembic commands ###
